! Populate path name/label arrays
slabCount = 4+CulvertCells-1

*del , path_names_m  ,      , nopr
*del , path_labels_m ,      , nopr
*del , path_names_n  ,      , nopr
*del , path_labels_n ,      , nopr
*del , path_names_v  ,      , nopr
*del , path_labels_v ,      , nopr
*dim , path_names_m  , char , slabCount
*dim , path_labels_m , char , slabCount
*dim , path_names_n  , char , slabCount
*dim , path_labels_n , char , slabCount
*dim , path_names_v  , char , slabCount
*dim , path_labels_v , char , slabCount

path_names_m(1)  = 'MN_Top_T' , 'MN_Bot_T' , 'MN_Lft_T' , 'MN_Rgt_T'
path_names_n(1)  = 'MN_Lft_T' , 'MN_Rgt_T' , 'MN_Top_T' , 'MN_Bot_T'
path_names_v(1)  = 'V_Top'    , 'V_Bot'    , 'V_Lft'    , 'V_Rgt'
path_labels_m(1) = 'MKNM'     , 'MKNM'     , 'MKNM'     , 'MKNM'
path_labels_n(1) = 'NKN'      , 'NKN'      , 'NKN'      , 'NKN'
path_labels_v(1) = 'VKN'      , 'VKN'      , 'VKN'      , 'VKN'

*if,CulvertCells,gt,1,then
  *do,nthCell,1,CulvertCells-1,1
    idx                = 4+nthCell
    path_names_m(idx)  = strcat('MN_In',strcat(chrval(nthCell),'_T'))
    path_names_n(idx)  = strcat('MN_In',strcat(chrval(nthCell),'_T'))
    path_names_v(idx)  = strcat('V_In',strcat(chrval(nthCell),'_T'))
    path_labels_m(idx) = 'MKNM'
    path_labels_n(idx) = 'NKN'
    path_labels_v(idx) = 'VKN'
  *enddo
*endif

! Scale paths from N to kN
*do,i,1,slabCount,1
  name = path_names_m(i)
  path,%name%
  pcalc,add,'MKNM','M',,1e-3

  name = path_names_n(i)
  path,%name%
  pcalc,add,'NKN','N',,1e-3

  name = path_names_v(i)
  path,%name%
  pcalc,add,'VKN','V',,1e-3
*enddo

! Plot bending moment
BOXCULVERT_V0_PTHPLOTS , 'BENDING MOMENT [kNm]' , 2*CulvertCells , 'path_names_m' , 'path_labels_m' , 'memo_CULVERT_M'

! Plot axial force
BOXCULVERT_V0_PTHPLOTS , 'AXIAL FORCE [kN]' , 2*CulvertCells , 'path_names_n' , 'path_labels_n' , 'memo_CULVERT_N'

! Plot shear force
BOXCULVERT_V0_PTHPLOTS , 'SHEAR FORCE [kN]' , 2*CulvertCells , 'path_names_v' , 'path_labels_v' , 'memo_CULVERT_V'

! Plot vertical displacement
/annot,dele
view1w
windefa,1
wincln,1
/plopts,leg3,on
/udoc,1,cntr,right
/gformat,f,1,1
/dscale,1,1

cmsel,s,COMPA_culvert
esla,s
nsle,s,1
/auto,1
pldisp
/user,1
/dist,1,1.2,1
clims

wintitle,1,' ','VERTICAL DISPLACEMENTS [mm]',' ',,1,13

go2png,1200
  allsel
  /device,vector,on
  /edge,,1
  pldisp
  /noerase
  /device,vector,off
  cmsel,s,COMPA_culvert
  esla
  nsle,,1
  cleanplot,'plnsol','u','y',,,,,,1e3
endpng,'memo_CULVERT_UY'

/erase
/annot,dele
view1w
