boldfont,1


! Soil pressures at concrete interfaces
view1w
windefa,1
wincln,1
wintitle,1,' ','SOIL PRESSURES [kPa]',' ',,1,13

/view,1,0,0,1
/plopts,leg3,on
/udoc,1,cntr,right
/gformat,f,1,1
/edge,1,1

*del , MPATHPLOT_ARR_pathNames
*dim , MPATHPLOT_ARR_pathNames , char , 4
*del , MPATHPLOT_ARR_labels
*dim , MPATHPLOT_ARR_labels    , char , 4
MPATHPLOT_ARR_pathNames(1) = 'SoilTop' , 'SoilBot' , 'SoilLeft' , 'SoilRight'
MPATHPLOT_ARR_labels(1)    = 'SYKPA'   , 'SYKPA'   , 'SXKPA'    , 'SXKPA'

go2png,1200
  allsel
  /auto,1
  /device,vector,on
  eplot
  /user,1
  /noerase
  /device,vector,off
  cleanplot,'mpathplot','4'
endpng,'memo_SOIL_PRES'

/erase
/annot,dele
view1w
windefa,1

! Soilbed SY
view1w
windefa,1
wincln,1
wintitle,1,' ','SOIL BED PRESSURES [kPa]',' ',,1,13

/view,1,0,0,1
/plopts,leg3,on
/udoc,1,cntr,right
/gformat,f,1,1
/edge,1,1

*del,MPATHPLOT_ARR_pathNames
*dim,MPATHPLOT_ARR_pathNames,char,3
*del,MPATHPLOT_ARR_labels
*dim,MPATHPLOT_ARR_labels,char,3
MPATHPLOT_ARR_pathNames(1) = 'BedLeft' , 'BedCntr' , 'BedRight'
MPATHPLOT_ARR_labels(1)    = 'SYKPA'   , 'SYKPA'   , 'SYKPA'

go2png,1200
  allsel
  /auto,1
  /device,vector,on
  eplot
  /user,1
  /noerase
  /device,vector,off
  cleanplot,'mpathplot','4'
endpng,'memo_SOILBED_SY'

/erase
/annot,dele
view1w
windefa,1

! First principal stress
view1w
windefa,1
wincln,1
clims
/view,1,0,0,1
/edge,,0
/udoc,1,cntr,right
/plopts,leg3,on
/gformat,f,1,1

wintitle,1,' ','FIRST PRINCIPAL STRESS S1 [kPa]',' ',,1,13

allsel
/auto,1
/dscale,1,auto
pldisp
/dscale,1,user
/user,1

go2png,1200
  /device,vector,on
  /edge,,1
  CMSEL,S,COMPA_culvert
  esla,s
  nsle,s
  pldisp
  /noerase
  /device,vector,off
  CMSEL,S,COMPA_SoilSubs
  CMSEL,A,COMPA_SoilRefill
  CMSEL,A,COMPA_SoilBase
  CMSEL,A,COMPA_SoilBed
  ESLA,S
  nsle,s
  cleanplot,'pletab','S1KPA','avg'
endpng,'memo_SOIL_S1'
/erase
/annot,dele
view1w

! Plastic strain
view1w
windefa,1
wincln,1
clims
/view,1,0,0,1
/edge,,0
/udoc,1,cntr,right
/plopts,leg3,on
/gformat,f,1,1

wintitle,1,' ','1st PLASTIC STRAIN (e1 x 1000)',' ',,1,13

allsel
/auto,1
/dscale,1,auto
pldisp
/dscale,1,user
/user,1

go2png,1200
  /device,vector,on
  /edge,,1
  CMSEL,S,COMPA_culvert
  esla,s
  nsle,s
  pldisp
  /noerase
  /device,vector,off
  CMSEL,S,COMPA_SoilSubs
  CMSEL,A,COMPA_SoilRefill
  CMSEL,A,COMPA_SoilBase
  CMSEL,A,COMPA_SoilBed
  ESLA,S
  nsle,s
  cleanplot,'plnsol','eppl','1','avg',,,,,1e3
endpng,'memo_SOIL_EPPL1'
/erase
/annot,dele
view1w
