! BOXCULVERT_V0_POSTCULVERTPATHS


! Get culvert corner nodes
cmsel,s,COMPA_culvert
nsla,s,1

N10 = node(X4,Y2,0)
N11 = node(X3,Y1,0)
N12 = node(X3,Y2,0)
N13 = node(X4,Y1,0)

N20 = node(X5,Y2,0)
N21 = node(X6,Y1,0)
N22 = node(X6,Y2,0)
N23 = node(X5,Y1,0)

N30 = node(X4,Y3,0)
N31 = node(X3,Y4,0)
N32 = node(X3,Y3,0)
N33 = node(X4,Y4,0)

N40 = node(X5,Y3,0)
N41 = node(X6,Y4,0)
N42 = node(X6,Y3,0)
N43 = node(X5,Y4,0)

! Virtual cross-sections: calculate geometric properties
secProp_I = (SewerWallThk**3)/12
secProp_W = secProp_I/(SewerWallThk/2)
secProp_A = SewerWallThk

! Top slab
allsel
etable , 'SM_11' , s , x
etable , 'SM_12' , s , xy
etable , 'M11'   , s , z
pth2beam , n30 , n40 , n33 , n43 , 'ROOF' , 1 , 20 , secProp_W , secProp_A , 0 , 'none' , 1 , 1

! Bottom slab
allsel
etable , 'SM_11' , s , x
etable , 'SM_12' , s , xy
etable , 'M11'   , s , z
pth2beam , n20 , n10 , n23 , n13 , 'FLOOR' , 1 , 20 , secProp_W , secProp_A , 0 , 'none' , 1 , 1

! Left wall
allsel
etable , 'SM_11' , s , y
etable , 'SM_12' , s , xy
etable , 'M11'   , s , z
pth2beam , n10 , n30 , n12 , n32 , 'LEFT' , 1 , 20 , secProp_W , secProp_A , 0 , 'none' , 1 , 1

! Right wall
allsel
etable , 'SM_11' , s , y
etable , 'SM_12' , s , xy
etable , 'M11'   , s , z
pth2beam , n40 , n20 , n42 , n22 , 'RIGHT' , 1 , 20 , secProp_W , secProp_A , 0 , 'none' , 1 , 1

! Inner walls
*if,CulvertCells,gt,1,then
  allsel
  etable , 'SM_11' , s , y
  etable , 'SM_12' , s , xy
  etable , 'M11'   , s , z
  *do,nthCell,1,CulvertCells-1,1
    xLeft  = Xi(nthCell)
    xRight = Xj(nthCell)
    N_llc  = node(xLeft  , Y2 , 0)
    N_lrc  = node(xRight , Y2 , 0)
    N_ulc  = node(xLeft  , Y3 , 0)
    N_urc  = node(xRight , Y3 , 0)
    pth2beam , N_lrc , N_urc , N_llc , N_ulc , 'INW%nthCell%' , 1 , 20 , secProp_W , secProp_A , 0 , 'none' , 1 , 1
  *enddo
*endif

! ! Number of shear force cross-sections
! NSEL,S,LOC,X,X4,X5
! NSEL,R,LOC,Y,Y1
! *get,VSEC_horCount,NODE,,COUNT
! NSEL,S,LOC,X,X4
! NSEL,R,LOC,Y,Y2,Y3
! *get,VSEC_verCount,NODE,,COUNT
! CMSEL,S,COMPA_culvert
! ESLA,S
! NSLE,S,1
!
! ! Top slab
! *del,TOP_M
! *del,TOP_N
! *del,TOP_V
! *del,TOP_U
! *del,TOP_D
! *del,TOP_XG
! *del,TOP_XV
!
! PTHS2MN,N30,N40,N33,N43,'MN_Top','X',200,secProp_W,secProp_A,0
! PTH2ARR,'XG','TOP_XG'
! *voper,TOP_M,PTHS2MN_ARR_bendingMoment,DIV,1000
! *voper,TOP_N,PTHS2MN_ARR_axialForce,DIV,1000
!
! PTHS2V,N33,N43,N30,N40,'V_Top','XY',VSEC_horCount,,secProp_A,0
! PTH2ARR,'XG','TOP_XV'
! *voper,TOP_V,PTHS2V_ARR_shear,DIV,1000
!
! PTH2DFL,N30,N40,,,'DF_Top','Y',100,,0
! *vabs,1
! *voper,TOP_U,PTH2DFL_ARR_disp,MULT,1000
! *vabs,1
! *voper,TOP_D,PTH2DFL_ARR_defl,MULT,1000
! *vabs
!
! ! Bottom slab
! *del,BOT_M
! *del,BOT_N
! *del,BOT_V
! *del,BOT_U
! *del,BOT_D
! *del,BOT_XG
! *del,BOT_XV
!
! PTHS2MN,N20,N10,N23,N13,'MN_Bot','X',200,secProp_W,secProp_A,0
! PTH2ARR,'XG','BOT_XG'
! *voper,BOT_M,PTHS2MN_ARR_bendingMoment,DIV,1000
! *voper,BOT_N,PTHS2MN_ARR_axialForce,DIV,1000
!
! PTHS2V,N10,N20,N13,N23,'V_Bot','XY',VSEC_horCount,,secProp_A,0
! PTH2ARR,'XG','BOT_XV'
! *voper,BOT_V,PTHS2V_ARR_shear,DIV,1000
!
! PTH2DFL,N10,N20,,,'DF_Bot','Y',100,,0
! *vabs,1
! *voper,BOT_U,PTH2DFL_ARR_disp,MULT,1000
! *vabs,1
! *voper,BOT_D,PTH2DFL_ARR_defl,MULT,1000
! *vabs
!
! ! Left wall
! *del,LFT_M
! *del,LFT_N
! *del,LFT_V
! *del,LFT_YG
! *del,LFT_YV
!
! PTHS2MN,N10,N30,N12,N32,'MN_Lft','Y',200,secProp_W,secProp_A,0
! PTH2ARR,'YG','LFT_YG'
! *voper,LFT_M,PTHS2MN_ARR_bendingMoment,DIV,1000
! *voper,LFT_N,PTHS2MN_ARR_axialForce,DIV,1000
!
! PTHS2V,N12,N32,N10,N30,'V_Lft','XY',VSEC_verCount,,secProp_A,0
! PTH2ARR,'YG','LFT_YV'
! *voper,LFT_V,PTHS2V_ARR_shear,DIV,1000
!
! ! Right wall
! *del,RGT_M
! *del,RGT_N
! *del,RGT_V
! *del,RGT_YG
! *del,RGT_YV
!
! PTHS2MN,N40,N20,N42,N22,'MN_Rgt','Y',200,secProp_W,secProp_A,0
! PTH2ARR,'YG','RGT_YG'
! *voper,RGT_M,PTHS2MN_ARR_bendingMoment,DIV,1000
! *voper,RGT_N,PTHS2MN_ARR_axialForce,DIV,1000
!
! PTHS2V,N20,N40,N22,N42,'V_Rgt','XY',VSEC_verCount,,secProp_A,0
! PTH2ARR,'YG','RGT_YV'
! *voper,RGT_V,PTHS2V_ARR_shear,DIV,1000
!
! ! Inner walls
! *if,CulvertCells,GT,1,THEN
!   *del,INN_M_table
!   *del,INN_N_table
!   *del,INN_V_table
!   *dim,INN_M_table,ARRAY,200,CulvertCells-1
!   *dim,INN_N_table,ARRAY,200,CulvertCells-1
!   *dim,INN_V_table,ARRAY,VSEC_verCount,CulvertCells-1
!   *do,nthCell,1,CulvertCells-1,1
!     xLeft=Xi(nthCell)
!     xRight=Xj(nthCell)
!     N_llc=NODE(xLeft,Y2,0)
!     N_lrc=NODE(xRight,Y2,0)
!     N_ulc=NODE(xLeft,Y3,0)
!     N_urc=NODE(xRight,Y3,0)
!
!     MNpathName=STRCAT('MN_In',CHRVAL(nthCell))
!     VpathName=STRCAT('V_In',CHRVAL(nthCell))
!
!     *del,nthINN_M
!     *del,nthINN_N
!     *del,nthINN_V
!     *del,INN_YG
!     *del,INN_YV
!
!     PTHS2MN,N_lrc,N_urc,N_llc,N_ulc,MNpathName,'Y',200,secProp_W,secProp_A,0
!     PTH2ARR,'YG','INN_YG'
!     *voper,nthINN_M,PTHS2MN_ARR_bendingMoment,DIV,1000
!     *voper,nthINN_N,PTHS2MN_ARR_axialForce,DIV,1000
!
!     PTHS2V,N_llc,N_ulc,N_lrc,N_urc,VpathName,'XY',VSEC_verCount,,secProp_A,0
!     PTH2ARR,'YG','INN_YV'
!     *voper,nthINN_V,PTHS2V_ARR_shear,DIV,1000
!
!     *do,nthValue,1,200,1
!       INN_M_table(nthValue,nthCell)=nthINN_M(nthValue)
!       INN_N_table(nthValue,nthCell)=nthINN_N(nthValue)
!     *enddo
!     *do,nthValue,1,VSEC_verCount,1
!       INN_V_table(nthValue,nthCell)=nthINN_V(nthValue)
!     *enddo
!   *enddo
! *endif
