! BOXCULVERT_V1_POSTCONTOURS


! Display mode
allsel
view1w
windefa,1
/view,1,0,0,1
/dscale,1,auto
/auto,1
/type,,3
/edge,,0
/plopts,MINM,0
/plopts,DATE,OFF
clims

! Global X and Y displacements
plnsol,u,y
takepic,'UY'
plnsol,u,x
takepic,'UX'

! Soil stresses & strains
cmsel,s,COMPA_SoilSubs
cmsel,a,COMPA_SoilRefill
cmsel,a,COMPA_SoilBase
cmsel,a,COMPA_SoilBed
esla,s

plnsol,s,x
takepic,'SOIL_SX'

plnsol,s,y
takepic,'SOIL_SY'

plnsol,s,xy
takepic,'SOIL_SXY'

clims,-1,1
plnsol,s,1
takepic,'SOIL_S1b'
clims

plnsol,epto,eqv
takepic,'SOIL_EPTO'
