! BOXCULVERT_V1_WRRES


! Define end/span zones
LEFT_b  = X3
LEFT_e  = X4+SewerWidth/4
RIGHT_b = X5-SewerWidth/4
RIGHT_e = X6

*del , HENDS_b ,  , nopr
*del , HENDS_e ,  , nopr
*dim , HENDS_b ,  , 2
*dim , HENDS_e ,  , 2
HENDS_b(1) = LEFT_b , RIGHT_b
HENDS_e(1) = LEFT_e , RIGHT_e

*del , INNER_b ,  , nopr
*del , INNER_e ,  , nopr
*dim , INNER_b ,  , CulvertCells-1
*dim , INNER_e ,  , CulvertCells-1
*do,nthCell,1,CulvertCells-1,1
  beg              = Xi(nthCell)-SewerWidth/4
  end              = Xj(nthCell)+SewerWidth/4
  INNER_b(nthCell) = beg
  INNER_e(nthCell) = end
*enddo

BOTTOM_b = Y1
BOTTOM_e = Y2+SewerHeight/4
TOP_b    = Y3-SewerHeight/4
TOP_e    = Y4

*del , VENDS_b ,  , nopr
*del , VENDS_e ,  , nopr
*dim , VENDS_b ,  , 2
*dim , VENDS_e ,  , 2
VENDS_b(1) = BOTTOM_b , TOP_b
VENDS_e(1) = BOTTOM_e , TOP_e

! Slab spans
*del , SLABSPAN_b ,  , nopr
*del , SLABSPAN_e ,  , nopr
*dim , SLABSPAN_b ,  , CulvertCells
*dim , SLABSPAN_e ,  , CulvertCells
*do,nthCell,1,CulvertCells,1
  beg                 = Xi(nthCell)-(3*SewerWidth/4)
  end                 = beg+(SewerWidth/2)
  SLABSPAN_b(nthCell) = beg
  SLABSPAN_e(nthCell) = end
*enddo

WALLSPAN_b = Y2+(SewerHeight/4)
WALLSPAN_e = Y3-(SewerHeight/4)

! Collect values from envelopes
*vfun , roof_mp_min , copy , roof_envelope(1 , 1)
*vfun , roof_mp_max , copy , roof_envelope(1 , 2)
*vfun , roof_n_min  , copy , roof_envelope(1 , 5)
*vfun , roof_n_max  , copy , roof_envelope(1 , 6)
*vfun , roof_v_max  , copy , roof_envelope(1 , 7)
*vfun , roof_v_min  , copy , roof_envelope(1 , 8)
*vfun , roof_d_max  , copy , roof_envelope(1 , 11)
*vfun , roof_d_min  , copy , roof_envelope(1 , 12)
path,ROOF
pth2arr,'XG','ROOF_XG'

*vfun , floor_mp_min , copy , floor_envelope(1 , 1)
*vfun , floor_mp_max , copy , floor_envelope(1 , 2)
*vfun , floor_n_min  , copy , floor_envelope(1 , 5)
*vfun , floor_n_max  , copy , floor_envelope(1 , 6)
*vfun , floor_v_max  , copy , floor_envelope(1 , 7)
*vfun , floor_v_min  , copy , floor_envelope(1 , 8)
*vfun , floor_d_max  , copy , floor_envelope(1 , 11)
*vfun , floor_d_min  , copy , floor_envelope(1 , 12)
path,FLOOR
pth2arr,'XG','FLOOR_XG'

*vfun , left_mp_min , copy , left_envelope(1 , 1)
*vfun , left_mp_max , copy , left_envelope(1 , 2)
*vfun , left_n_min  , copy , left_envelope(1 , 5)
*vfun , left_n_max  , copy , left_envelope(1 , 6)
*vfun , left_v_max  , copy , left_envelope(1 , 7)
*vfun , left_v_min  , copy , left_envelope(1 , 8)
*vfun , left_d_max  , copy , left_envelope(1 , 9)
*vfun , left_d_min  , copy , left_envelope(1 , 10)
path,LEFT
pth2arr,'YG','LEFT_YG'

*vfun , right_mp_min , copy , right_envelope(1 , 1)
*vfun , right_mp_max , copy , right_envelope(1 , 2)
*vfun , right_n_min  , copy , right_envelope(1 , 5)
*vfun , right_n_max  , copy , right_envelope(1 , 6)
*vfun , right_v_max  , copy , right_envelope(1 , 7)
*vfun , right_v_min  , copy , right_envelope(1 , 8)
*vfun , right_d_max  , copy , right_envelope(1 , 9)
*vfun , right_d_min  , copy , right_envelope(1 , 10)
path,RIGHT
pth2arr,'YG','RIGHT_YG'

*if,CulvertCells,GT,1,THEN
  *vfun , iwall_mp_min , copy , iwall_envelope(1 , 1)
  *vfun , iwall_mp_max , copy , iwall_envelope(1 , 2)
  *vfun , iwall_n_min  , copy , iwall_envelope(1 , 5)
  *vfun , iwall_n_max  , copy , iwall_envelope(1 , 6)
  *vfun , iwall_v_max  , copy , iwall_envelope(1 , 7)
  *vfun , iwall_v_min  , copy , iwall_envelope(1 , 8)
  *vfun , iwall_d_max  , copy , iwall_envelope(1 , 9)
  *vfun , iwall_d_min  , copy , iwall_envelope(1 , 10)
  path,IWALL1
  pth2arr,'YG','IWALL_YG'
*endif

! Roof
vmfun , 'ROOF_Mmax_ends'  , 'roof_mp_max' , 'MAX'    , 'ROOF_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'ROOF_Mmin_ends'  , 'roof_mp_min' , 'MIN'    , 'ROOF_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'ROOF_Mmax_span'  , 'roof_mp_max' , 'MAX'    , 'ROOF_XG' , 'SLABSPAN_b' , 'SLABSPAN_e'
vmfun , 'ROOF_Mmin_span'  , 'roof_mp_min' , 'MIN'    , 'ROOF_XG' , 'SLABSPAN_b' , 'SLABSPAN_e'
vmfun , 'ROOF_Mmax_inner' , 'roof_mp_max' , 'MAX'    , 'ROOF_XG' , 'INNER_b'    , 'INNER_e'
vmfun , 'ROOF_Mmin_inner' , 'roof_mp_min' , 'MIN'    , 'ROOF_XG' , 'INNER_b'    , 'INNER_e'

vmfun , 'ROOF_Nmax_ends'  , 'roof_n_max'  , 'MAX'    , 'ROOF_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'ROOF_Nmin_ends'  , 'roof_n_min'  , 'MIN'    , 'ROOF_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'ROOF_Nmax_span'  , 'roof_n_max'  , 'MAX'    , 'ROOF_XG' , 'SLABSPAN_b' , 'SLABSPAN_e'
vmfun , 'ROOF_Nmin_span'  , 'roof_n_min'  , 'MIN'    , 'ROOF_XG' , 'SLABSPAN_b' , 'SLABSPAN_e'
vmfun , 'ROOF_Nmax_inner' , 'roof_n_max'  , 'MAX'    , 'ROOF_XG' , 'INNER_b'    , 'INNER_e'
vmfun , 'ROOF_Nmin_inner' , 'roof_n_min'  , 'MIN'    , 'ROOF_XG' , 'INNER_b'    , 'INNER_e'

vmfun , 'ROOF_Vmax_ends'  , 'roof_v_max'  , 'ABSMAX' , 'ROOF_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'ROOF_Vmin_ends'  , 'roof_v_min'  , 'ABSMIN' , 'ROOF_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'ROOF_Vmax_inner' , 'roof_v_max'  , 'ABSMAX' , 'ROOF_XG' , 'INNER_b'    , 'INNER_e'
vmfun , 'ROOF_Vmin_inner' , 'roof_v_min'  , 'ABSMIN' , 'ROOF_XG' , 'INNER_b'    , 'INNER_e'

*vscfun , ROOF_Dmax , max , roof_d_max
*vscfun , ROOF_Dmin , max , roof_d_min

! Floor
vmfun , 'FLOOR_Mmax_ends'  , 'floor_mp_max' , 'MAX'    , 'FLOOR_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'FLOOR_Mmin_ends'  , 'floor_mp_min' , 'MIN'    , 'FLOOR_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'FLOOR_Mmax_span'  , 'floor_mp_max' , 'MAX'    , 'FLOOR_XG' , 'SLABSPAN_b' , 'SLABSPAN_e'
vmfun , 'FLOOR_Mmin_span'  , 'floor_mp_min' , 'MIN'    , 'FLOOR_XG' , 'SLABSPAN_b' , 'SLABSPAN_e'
vmfun , 'FLOOR_Mmax_inner' , 'floor_mp_max' , 'MAX'    , 'FLOOR_XG' , 'INNER_b'    , 'INNER_e'
vmfun , 'FLOOR_Mmin_inner' , 'floor_mp_min' , 'MIN'    , 'FLOOR_XG' , 'INNER_b'    , 'INNER_e'

vmfun , 'FLOOR_Nmax_ends'  , 'floor_n_max'  , 'MAX'    , 'FLOOR_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'FLOOR_Nmin_ends'  , 'floor_n_min'  , 'MIN'    , 'FLOOR_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'FLOOR_Nmax_span'  , 'floor_n_max'  , 'MAX'    , 'FLOOR_XG' , 'SLABSPAN_b' , 'SLABSPAN_e'
vmfun , 'FLOOR_Nmin_span'  , 'floor_n_min'  , 'MIN'    , 'FLOOR_XG' , 'SLABSPAN_b' , 'SLABSPAN_e'
vmfun , 'FLOOR_Nmax_inner' , 'floor_n_max'  , 'MAX'    , 'FLOOR_XG' , 'INNER_b'    , 'INNER_e'
vmfun , 'FLOOR_Nmin_inner' , 'floor_n_min'  , 'MIN'    , 'FLOOR_XG' , 'INNER_b'    , 'INNER_e'

vmfun , 'FLOOR_Vmax_ends'  , 'floor_v_max'  , 'ABSMAX' , 'FLOOR_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'FLOOR_Vmin_ends'  , 'floor_v_min'  , 'ABSMIN' , 'FLOOR_XG' , 'HENDS_b'    , 'HENDS_e'
vmfun , 'FLOOR_Vmax_inner' , 'floor_v_max'  , 'ABSMAX' , 'FLOOR_XG' , 'INNER_b'    , 'INNER_e'
vmfun , 'FLOOR_Vmin_inner' , 'floor_v_min'  , 'ABSMIN' , 'FLOOR_XG' , 'INNER_b'    , 'INNER_e'

*vscfun , FLOOR_Dmax , max , floor_d_max
*vscfun , FLOOR_Dmin , max , floor_d_min

! Left wall
vmfun , 'LEFT_Mmax_ends' , 'left_mp_max' , 'MAX'    , 'LEFT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'LEFT_Mmin_ends' , 'left_mp_min' , 'MIN'    , 'LEFT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'LEFT_Mmax_span' , 'left_mp_max' , 'MAX'    , 'LEFT_YG' , WALLSPAN_b , WALLSPAN_e
vmfun , 'LEFT_Mmin_span' , 'left_mp_min' , 'MIN'    , 'LEFT_YG' , WALLSPAN_b , WALLSPAN_e

vmfun , 'LEFT_Nmax_ends' , 'left_n_max'  , 'MAX'    , 'LEFT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'LEFT_Nmin_ends' , 'left_n_min'  , 'MIN'    , 'LEFT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'LEFT_Nmax_span' , 'left_n_max'  , 'MAX'    , 'LEFT_YG' , WALLSPAN_b , WALLSPAN_e
vmfun , 'LEFT_Nmin_span' , 'left_n_min'  , 'MIN'    , 'LEFT_YG' , WALLSPAN_b , WALLSPAN_e

vmfun , 'LEFT_Vmax_ends' , 'left_v_max'  , 'ABSMAX' , 'LEFT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'LEFT_Vmin_ends' , 'left_v_min'  , 'ABSMIN' , 'LEFT_YG' , 'VENDS_b'  , 'VENDS_e'

! Right wall
vmfun , 'RIGHT_Mmax_ends' , 'right_mp_max' , 'MAX'    , 'RIGHT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'RIGHT_Mmin_ends' , 'right_mp_min' , 'MIN'    , 'RIGHT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'RIGHT_Mmax_span' , 'right_mp_max' , 'MAX'    , 'RIGHT_YG' , WALLSPAN_b , WALLSPAN_e
vmfun , 'RIGHT_Mmin_span' , 'right_mp_min' , 'MIN'    , 'RIGHT_YG' , WALLSPAN_b , WALLSPAN_e

vmfun , 'RIGHT_Nmax_ends' , 'right_n_max'  , 'MAX'    , 'RIGHT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'RIGHT_Nmin_ends' , 'right_n_min'  , 'MIN'    , 'RIGHT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'RIGHT_Nmax_span' , 'right_n_max'  , 'MAX'    , 'RIGHT_YG' , WALLSPAN_b , WALLSPAN_e
vmfun , 'RIGHT_Nmin_span' , 'right_n_min'  , 'MIN'    , 'RIGHT_YG' , WALLSPAN_b , WALLSPAN_e

vmfun , 'RIGHT_Vmax_ends' , 'right_v_max'  , 'ABSMAX' , 'RIGHT_YG' , 'VENDS_b'  , 'VENDS_e'
vmfun , 'RIGHT_Vmin_ends' , 'right_v_min'  , 'ABSMIN' , 'RIGHT_YG' , 'VENDS_b'  , 'VENDS_e'

! Inner walls
*if,CulvertCells,GT,1,THEN

  vmfun , 'IWALL_Mmax_ends' , 'iwall_mp_max' , 'MAX'    , 'IWALL_YG' , 'VENDS_b'  , 'VENDS_e'
  vmfun , 'IWALL_Mmin_ends' , 'iwall_mp_min' , 'MIN'    , 'IWALL_YG' , 'VENDS_b'  , 'VENDS_e'
  vmfun , 'IWALL_Mmax_span' , 'iwall_mp_max' , 'MAX'    , 'IWALL_YG' , WALLSPAN_b , WALLSPAN_e
  vmfun , 'IWALL_Mmin_span' , 'iwall_mp_min' , 'MIN'    , 'IWALL_YG' , WALLSPAN_b , WALLSPAN_e

  vmfun , 'IWALL_Nmax_ends' , 'iwall_n_max'  , 'MAX'    , 'IWALL_YG' , 'VENDS_b'  , 'VENDS_e'
  vmfun , 'IWALL_Nmin_ends' , 'iwall_n_min'  , 'MIN'    , 'IWALL_YG' , 'VENDS_b'  , 'VENDS_e'
  vmfun , 'IWALL_Nmax_span' , 'iwallr_n_max' , 'MAX'    , 'IWALL_XG' , WALLSPAN_b , WALLSPAN_e
  vmfun , 'IWALL_Nmin_span' , 'iwallr_n_min' , 'MIN'    , 'IWALL_XG' , WALLSPAN_b , WALLSPAN_e

  vmfun , 'IWALL_Vmax_ends' , 'iwall_v_max'  , 'ABSMAX' , 'IWALL_YG' , 'VENDS_b'  , 'VENDS_e'
  vmfun , 'IWALL_Vmin_ends' , 'iwall_v_min'  , 'ABSMIN' , 'IWALL_YG' , 'VENDS_b'  , 'VENDS_e'

*else

  IWALL_Mmax_ends = 0
  IWALL_Mmin_ends = 0
  IWALL_Mmax_span = 0
  IWALL_Mmin_span = 0

  IWALL_Nmax_ends = 0
  IWALL_Nmin_ends = 0
  IWALL_Nmax_span = 0
  IWALL_Nmin_span = 0

  IWALL_Vmax_ends = 0
  IWALL_Vmin_ends = 0

*endif

! Soil
*vabs,1,1
*vscfun,SOIL_S_max,MAX,SOIL_S
*vabs,1
*vscfun,SOIL_S_avg,MEAN,SOIL_S
*vabs

! Combine outer wall results
OUT_Mmax_ends = (LEFT_Mmax_ends>RIGHT_Mmax_ends)
OUT_Mmin_ends = (LEFT_Mmin_ends<RIGHT_Mmin_ends)
OUT_Mmax_span = (LEFT_Mmax_span>RIGHT_Mmax_span)
OUT_Mmin_span = (LEFT_Mmin_span<RIGHT_Mmin_span)

OUT_Nmax_ends = (LEFT_Nmax_ends>RIGHT_Nmax_ends)
OUT_Nmin_ends = (LEFT_Nmin_ends<RIGHT_Nmin_ends)
OUT_Nmax_span = (LEFT_Nmax_span>RIGHT_Nmax_span)
OUT_Nmin_span = (LEFT_Nmin_span<RIGHT_Nmin_span)

OUT_Vmax_ends = (LEFT_Vmax_ends>RIGHT_Vmax_ends)
OUT_Vmin_ends = (LEFT_Vmin_ends<RIGHT_Vmin_ends)

! Write values to file
*cfopen,SOLU_reportFilename,TXT,,APPEND

  ! TODO  BOT_U_min, BOT_U_max: calculate
  !       Soil results: currently pulls from LT, needs to also collect DW

  ! Minimum values:
  *vwrite,SoilCover, SewerWallThk
  (F9.2,'  ',F8.2,'    ',\b)
  *vwrite , ROOF_Mmin_ends  , ROOF_Vmin_ends  , ROOF_Nmin_ends  , ROOF_Mmin_span  , ROOF_Nmin_span  , ROOF_Mmin_inner  , ROOF_Vmin_inner  , ROOF_Nmin_inner
  (F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'    ',\b)
  *vwrite , FLOOR_Mmin_ends , FLOOR_Vmin_ends , FLOOR_Nmin_ends , FLOOR_Mmin_span , FLOOR_Nmin_span , FLOOR_Mmin_inner , FLOOR_Vmin_inner , FLOOR_Nmin_inner
  (F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'    ',\b)
  *vwrite , OUT_Mmin_ends   , OUT_Vmin_ends   , OUT_Nmin_ends   , OUT_Mmin_span   , OUT_Nmin_span
  (F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'    ',\b)
  *vwrite , IWALL_Mmin_ends , IWALL_Vmin_ends , IWALL_Nmin_ends , IWALL_Mmin_span , IWALL_Nmin_span
  (F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'    ',\b)
  *vwrite , SOIL_S_avg*1e-3 , SOIL_S_max*1e-3 , 0               , BOT_U_min       , ROOF_Dmin       , FLOOR_Dmin
  (F8.1,'  ',F8.1,'  ',F8.3,'  ',F8.3,'  ',F8.3,'  ',F8.3)

  ! Maximum values:
  *vwrite,SoilCover, SewerWallThk
  (F9.2,'  ',F8.2,'    ',\b)
  *vwrite , ROOF_Mmax_ends  , ROOF_Vmax_ends  , ROOF_Nmax_ends  , ROOF_Mmax_span  , ROOF_Nmax_span  , ROOF_Mmax_inner  , ROOF_Vmax_inner  , ROOF_Nmax_inner
  (F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'    ',\b)
  *vwrite , FLOOR_Mmax_ends , FLOOR_Vmax_ends , FLOOR_Nmax_ends , FLOOR_Mmax_span , FLOOR_Nmax_span , FLOOR_Mmax_inner , FLOOR_Vmax_inner , FLOOR_Nmax_inner
  (F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'    ',\b)
  *vwrite , OUT_Mmax_ends   , OUT_Vmax_ends   , OUT_Nmax_ends   , OUT_Mmax_span   , OUT_Nmax_span
  (F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'    ',\b)
  *vwrite , IWALL_Mmax_ends , IWALL_Vmax_ends , IWALL_Nmax_ends , IWALL_Mmax_span , IWALL_Nmax_span
  (F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'  ',F8.1,'    ',\b)
  *vwrite , SOIL_S_avg*1e-3 , SOIL_S_max*1e-3 , 0               , BOT_U_max       , ROOF_Dmax       , FLOOR_Dmax
  (F8.1,'  ',F8.1,'  ',F8.3,'  ',F8.3,'  ',F8.3,'  ',F8.3)

*cfclos
