! Switch output to file
/output,outfile,out
init , 'BOXCULVERT_V1_DEFAULTS'

! Display options
/prep7
/uis,MSGPOP,3
/uis,REPLOT,0
IMMED,0
/vup,ALL,Y
/plopts,DATE,OFF
/device,VECTOR,OFF

! Colors for material-based plot
/color,NUM,DGRA,1
/color,NUM,BMAG,2
/color,NUM,MRED,3
/color,NUM,CBLU,4
/color,NUM,ORAN,5
/color,NUM,GREE,6
/color,NUM,YELL,7
/color,NUM,CBLU,8
/color,NUM,YGRE,9
/color,NUM,BLUE,10
/color,NUM,GCYA,11

! Create results folder to store images
/inquire,currDir,DIRECTORY
*del,imgFolderPath
*dim,imgFolderPath,STRING,248
imgFolderName=FILE_name
imgFolderPath(1)=STRCAT(currDir(1),STRCAT('\',imgFolderName))
/syp,mkdir,imgFolderName

! Folder for results from first load step (dead weight)
*del,dwFolderPath
*dim,dwFolderPath,STRING,248
dwFolderName='DW'
dwFolderPath(1)=STRCAT(imgFolderPath(1),STRCAT('\',dwFolderName))
/cwd,'%imgFolderPath(1)%'
/syp,mkdir,dwFolderName
/cwd,'%currDir(1)%'

! Folder for results from second load step (load train)
*do,nthPos,1,LOADTRAIN_posCount,1
  *del,ltFolderPath%nthPos%,,nopr
  *dim,ltFolderPath%nthPos%,string,248
  ltFolderName            = 'LT_%nthPos%'
  ltFolderPath%nthPos%(1) = strcat(imgFolderPath(1),strcat('\',ltFolderName))
  /cwd,'%imgFolderPath(1)%'
  /syp,mkdir,ltFolderName
*enddo
/cwd,'%currDir(1)%'

!!
!!
!! 2. ATTRIBUTES
!!
!!
BOXCULVERT_V1_ATTR





!!
!!
!! 3. SOLID MODEL
!!
!!
BOXCULVERT_V1_SM





!!
!!
!! 4. FINITE ELEMENT MODEL
!!
!!
BOXCULVERT_V1_FEM





!!
!!
!! 5. BOUNDARY CONDITIONS
!!
!!
BOXCULVERT_V1_BC
SAVE,,,,ALL





!!
!!
!! 7. POST-PROCESS
!!
!!
/post1

! Report file: initialize
*if,SOLU_reportMode,EQ,0,THEN
  BOXCULVERT_V1_REPHDR
*endif

*if,SewerType,NE,2,THEN

  *del , roof_envelope  ,  , nopr
  *del , floor_envelope ,  , nopr
  *del , left_envelope  ,  , nopr
  *del , right_envelope ,  , nopr
  *del , iwall_envelope ,  , nopr
  padele,all

  BOXCULVERT_V1_REPHDR

  ! Results from first load step (dead weight)
  set,1,last
  /cwd,'%dwFolderPath(1)%'
  BOXCULVERT_V1_POST
  /cwd,'%currDir(1)%'
  BOXCULVERT_V1_WRRES

  ! Results from second load step (load train)
  *do,nthLS,2,lastLS,1
    set,nthLS,last
    posIdx = nthLS-1
    /cwd,ltFolderPath%posIdx%(1)
    BOXCULVERT_V1_POST
    /cwd,'%currDir(1)%'
  *enddo
  BOXCULVERT_V1_WRRES

*else
  /post1
  SET,LAST
  ALLSEL
  /auto,1
  /type,,3
  /edge,,0
  /plopts,MINM,0
  /plopts,DATE,OFF
  baseScale=SewerOuterWidth+SewerOuterHeight
  /device,VECTOR,OFF
  /edge,,0
  /uis,MSGPOP,3
  ALLSEL
  CMSEL,S,COMPA_SoilSubs
  CMSEL,A,COMPA_SoilBase
  CMSEL,A,COMPA_SoilRefill
  CMSEL,A,COMPA_SoilBed
  ESLA,S
  NSLE,S
  PATH,'SoilTop',2,20,200
  PPATH,1,,X9,Y4,0
  PPATH,2,,X0,Y4,0
  PATH,'SoilTop'
  BOXCULVERT_V1_PTHMAP
  PLPAGM,SY,10,NODE

*endif

*msg,UI,
DONE!
