! BOXCULVERT_V0_PTHPLOTS , title , scale , path_names , path_labels , fname
! BOXCULVERT_V0_PTHPLOTS , ARG1  , ARG2  , ARG3       , ARG4        , ARG5


_title         = ARG1
_scale         = ARG2
_path_names    = ARG3
_path_labels   = ARG4
_fname         = ARG5
pathNamesStr   = _path_names
pathLabelsStr  = _path_labels
namesContainer = 'pathNamesStr'
labelContainer = 'pathLabelsStr'

cmsel,s,COMPA_culvert
esla,s
nsle,s,1

view1w
wincln,1
boldfont,1
clims
wintitle,1,' ',_title,' ',,1,13

/view,1,0,0,1
/plopts,leg3,on
/udoc,1,cntr,right
/gformat,f,1,1
/edge,1,1
/auto,1
nplot
/user,1
/dist,1,1.2,1

go2png,1200
  /device,vector,on
  eplot
  /noerase
  /device,vector,off
  cleanplot,'mpathplot',_scale,,'namesContainer','labelContainer'
endpng,_fname

/erase
/annot,dele
view1w
windefa,1
clims
boldfont
