! BOXCULVERT_V0_POST


/post1

! Element tables
allsel
etable,'SY',s,y
etable,'SX',s,x

etable,'S1',s,1
sadd,'S1KPA','S1',,1e-3

! Contour plots
BOXCULVERT_V0_POSTCONTOURS


! Path plots
baseScale = SewerOuterWidth+SewerOuterHeight
/device,vector,off
/edge,,0
/uis,msgpop,3
allsel

! Soil results
BOXCULVERT_V0_POSTSOILPATHS

! Culvert results
BOXCULVERT_V0_POSTCULVERTPATHS


!! memo images
BOXCULVERT_V0_POSTCULVERT
/input , 'D:\Tools\Code\box-culvert-2D\_plot_soil_pres' , mac
