! BOXCULVERT_V1_POSTSOILPATHS


! Create paths
cmsel,s,COMPA_SoilSubs
cmsel,a,COMPA_SoilBase
cmsel,a,COMPA_SoilRefill
cmsel,a,COMPA_SoilBed
esla,s
nsle,s

! Top slab
path,'SoilTop',2,20,200
ppath,1,,X9,Y4,0
ppath,2,,X0,Y4,0
path,'SoilTop'
BOXCULVERT_V1_PTHMAP

! Bottom slab
path,'SoilBot',2,20,200
ppath,1,,X0,Y1,0
ppath,2,,X9,Y1,0
path,'SoilBot'
BOXCULVERT_V1_PTHMAP

! Left wall
path,'SoilLeft',2,20,200
ppath,1,,X3,Y12,0
ppath,2,,X3,Y0,0
path,'SoilLeft'
BOXCULVERT_V1_PTHMAP

! Right wall
path,'SoilRight',2,20,200
ppath,1,,X6,Y0,0
ppath,2,,X6,Y12,0
path,'SoilRight'
BOXCULVERT_V1_PTHMAP

! Foundation (left side)
path,'BedLeft',2,20,200
ppath,1,,X3,Y1,0
ppath,2,,X3,Y0,0
path,'BedLeft'
BOXCULVERT_V1_PTHMAP

! Foundation (center)
path,'BedCntr',2,20,200
ppath,1,,(X4+X5)/2,Y1,0
ppath,2,,(X4+X5)/2,Y0,0
path,'BedCntr'
BOXCULVERT_V1_PTHMAP

! Foundation (right side)
path,'BedRight',2,20,200
ppath,1,,X6,Y1,0
ppath,2,,X6,Y0,0
path,'BedRight'
BOXCULVERT_V1_PTHMAP

!! 7.2.1.2 COLLECT RESULTS
path,'SoilBot'
pth2arr,'SY','SOIL_S'
