! BOXCULVERT_V0_POSTSOILPATHS


! Create paths
cmsel,s,COMPA_SoilSubs
cmsel,a,COMPA_SoilBase
cmsel,a,COMPA_SoilRefill
cmsel,a,COMPA_SoilBed
esla,s
nsle,s

! Top slab
path,'SoilTop',2,20,200
ppath,1,,X9,Y4,0
ppath,2,,X0,Y4,0
path,'SoilTop'
SEWERSECT_V0_PTHMAP

! Bottom slab
path,'SoilBot',2,20,200
ppath,1,,X0,Y1,0
ppath,2,,X9,Y1,0
path,'SoilBot'
SEWERSECT_V0_PTHMAP

! Left wall
path,'SoilLeft',2,20,200
ppath,1,,X3,Y12,0
ppath,2,,X3,Y0,0
path,'SoilLeft'
SEWERSECT_V0_PTHMAP

! Right wall
path,'SoilRight',2,20,200
ppath,1,,X6,Y0,0
ppath,2,,X6,Y12,0
path,'SoilRight'
SEWERSECT_V0_PTHMAP

! Foundation (left side)
path,'BedLeft',2,20,200
ppath,1,,X3,Y1,0
ppath,2,,X3,Y0,0
path,'BedLeft'
SEWERSECT_V0_PTHMAP

! Foundation (center)
path,'BedCntr',2,20,200
ppath,1,,(X4+X5)/2,Y1,0
ppath,2,,(X4+X5)/2,Y0,0
path,'BedCntr'
SEWERSECT_V0_PTHMAP

! Foundation (right side)
path,'BedRight',2,20,200
ppath,1,,X6,Y1,0
ppath,2,,X6,Y0,0
path,'BedRight'
SEWERSECT_V0_PTHMAP

!! 7.2.1.2 COLLECT RESULTS
path,'SoilBot'
pth2arr,'SY','SOIL_S'
