! BOXCULVERT_V0_PTHPLOTS , title , scale , fname
! BOXCULVERT_V0_PTHPLOTS , ARG1  , ARG2  , ARG3



!    *del,MPATHPLOT_ARR_pathNames
!    *dim,MPATHPLOT_ARR_pathNames,char,4
!    *del,MPATHPLOT_ARR_labels
!    *dim,MPATHPLOT_ARR_labels,char,4
!
!    MPATHPLOT_ARR_pathNames(1)=       'SoilTop',       'SoilBot',      'SoilLeft',     'SoilRight'
!    MPATHPLOT_ARR_labels(1)=            'SYKPA',         'SYKPA',         'SXKPA',         'SXKPA'

_title = ARG1
_scale = ARG2
_fname = ARG3

cmsel,s,COMPA_culvert
esla,s
nsle,s,1

view1w
boldfont,1
wincln,1
wintitle,1,' ',_title,' ',,1,13

/view,1,0,0,1
/plopts,leg3,on
/udoc,1,cntr,right
/gformat,f,1,1
/edge,1,1
/auto,1
nplot
/user,1
/dist,1,1.2,1

go2png,1200
  /device,vector,on
  eplot
  /noerase
  /device,vector,off
  cleanplot,'mpathplot',_scale
endpng,_fname

/erase
/annot,dele
view1w
windefa,1
