! BOXCULVERT_V1_POSTCULVERTPATHS


! Get culvert corner nodes
cmsel,s,COMPA_culvert
nsla,s,1

N10 = node(X4,Y2,0)
N11 = node(X3,Y1,0)
N12 = node(X3,Y2,0)
N13 = node(X4,Y1,0)

N20 = node(X5,Y2,0)
N21 = node(X6,Y1,0)
N22 = node(X6,Y2,0)
N23 = node(X5,Y1,0)

N30 = node(X4,Y3,0)
N31 = node(X3,Y4,0)
N32 = node(X3,Y3,0)
N33 = node(X4,Y4,0)

N40 = node(X5,Y3,0)
N41 = node(X6,Y4,0)
N42 = node(X6,Y3,0)
N43 = node(X5,Y4,0)

! Virtual cross-sections: calculate geometric properties
secProp_I = (SewerWallThk**3)/12
secProp_W = secProp_I/(SewerWallThk/2)
secProp_A = SewerWallThk

! Create part selection components
nsel,s,loc,x,x4,x5
nsel,r,loc,y,y3,y4
cmsel,s,COMPA_culvert
esla
esln,r,1
cm,COMPN_roof,node
cm,COMPE_roof,elem

nsel,s,loc,x,x4,x5
nsel,r,loc,y,y1,y2
cmsel,s,COMPA_culvert
esla
esln,r,1
cm,COMPN_floor,node
cm,COMPE_floor,elem

nsel,s,loc,x,x3,x4
nsel,r,loc,y,y2,y3
esla
esln,r,1
cm,COMPN_left,node
cm,COMPE_left,elem

nsel,s,loc,x,x5,x6
nsel,r,loc,y,y2,y3
esla
esln,r,1
cm,COMPN_right,node
cm,COMPE_right,elem

nsel,s,loc,x,x4,x5
nsel,u,loc,x,x4
nsel,u,loc,x,x5
nsel,r,loc,y,y2,y3
esla
esln,r,1
cm,COMPN_iwall,node
cm,COMPE_iwall,elem

! Top slab
cmsel,s,COMPN_roof
cmsel,s,COMPE_roof
etable , 'SM_11' , s , x
etable , 'SM_12' , s , xy
etable , 'M11'   , s , z
pth2beam , n43 , n33 , n40 , n30 , 'ROOF' , 1 , 20 , secProp_W , secProp_A , 0 , 'roof_envelope' , 1 , 2

! Bottom slab
cmsel,s,COMPN_floor
cmsel,s,COMPE_floor
etable , 'SM_11' , s , x
etable , 'SM_12' , s , xy
etable , 'M11'   , s , z
pth2beam , n13 , n23 , n10 , n20 , 'FLOOR' , 1 , 20 , secProp_W , secProp_A , 0 , 'floor_envelope' , 1 , 2

! Left wall
cmsel,s,COMPN_left
cmsel,s,COMPE_left
etable , 'SM_11' , s , y
etable , 'SM_12' , s , xy
etable , 'M11'   , s , z
pth2beam , n32 , n12 , n30 , n10 , 'LEFT' , 1 , 20 , secProp_W , secProp_A , 0 , 'left_envelope' , 1 , 2

! Right wall
cmsel,s,COMPN_right
cmsel,s,COMPE_right
etable , 'SM_11' , s , y
etable , 'SM_12' , s , xy
etable , 'M11'   , s , z
pth2beam , n22 , n42 , n20 , n40 , 'RIGHT' , -1 , 20 , secProp_W , secProp_A , 0 , 'right_envelope' , 1 , 2

! Inner walls
*if,CulvertCells,gt,1,then
  cmsel,s,COMPN_iwall
  cmsel,s,COMPE_iwall
  etable , 'SM_11' , s , y
  etable , 'SM_12' , s , xy
  etable , 'M11'   , s , z
  *do,nthCell,1,CulvertCells-1,1
    xLeft  = Xi(nthCell)
    xRight = Xj(nthCell)
    N_llc  = node(xLeft  , Y2 , 0)
    N_lrc  = node(xRight , Y2 , 0)
    N_ulc  = node(xLeft  , Y3 , 0)
    N_urc  = node(xRight , Y3 , 0)
    pth2beam , N_lrc , N_urc , N_llc , N_ulc , 'INW%nthCell%' , 1 , 20 , secProp_W , secProp_A , 0 , 'iwall_envelope' , 1 , 2
  *enddo
*endif
