! BOXCULVERT_V1_POSTSOILPATHS


labelCount = 40

! Create paths
cmsel,s,COMPA_SoilSubs
cmsel,a,COMPA_SoilBase
cmsel,a,COMPA_SoilRefill
cmsel,a,COMPA_SoilBed
esla,s
nsle,s

! Top slab
path,'SOIL_T',2,labelCount,200
ppath,1,,X9,Y4,0
ppath,2,,X0,Y4,0
path,'SOIL_T'
BOXCULVERT_V1_PTHMAP

! Bottom slab
path,'SOIL_B',2,labelCount,200
ppath,1,,X0,Y1,0
ppath,2,,X9,Y1,0
path,'SOIL_B'
BOXCULVERT_V1_PTHMAP

! Left wall
path,'SOIL_L',2,labelCount,200
ppath,1,,X3,Y12,0
ppath,2,,X3,Y0,0
path,'SOIL_L'
BOXCULVERT_V1_PTHMAP

! Right wall
path,'SOIL_R',2,labelCount,200
ppath,1,,X6,Y0,0
ppath,2,,X6,Y12,0
path,'SOIL_R'
BOXCULVERT_V1_PTHMAP

! Foundation (left side)
path,'BED_L',2,labelCount,200
ppath,1,,X3,Y1,0
ppath,2,,X3,Y0,0
path,'BED_L'
BOXCULVERT_V1_PTHMAP

! Foundation (center)
path,'BED_C',2,labelCount,200
ppath,1,,(X4+X5)/2,Y1,0
ppath,2,,(X4+X5)/2,Y0,0
path,'BED_C'
BOXCULVERT_V1_PTHMAP

! Foundation (right side)
path,'BED_R',2,labelCount,200
ppath,1,,X6,Y1,0
ppath,2,,X6,Y0,0
path,'BED_R'
BOXCULVERT_V1_PTHMAP

!! 7.2.1.2 COLLECT RESULTS
path,'SOIL_B'
pth2arr,'SY','SOIL_S'

pthenv,'UPDATE','soil_envelope'
