! BOXCULVERT_V0_POST


/post1

! Element tables
allsel
etable,'SY',s,y
etable,'SX',s,x

etable,'S1',s,1
sadd,'S1KPA','S1',,1e-3

! Contour plots
BOXCULVERT_V0_POSTCONTOURS


! Path plots
baseScale = SewerOuterWidth+SewerOuterHeight
/device,vector,off
/edge,,0
/uis,msgpop,3
allsel

! Soil results
BOXCULVERT_V0_POSTSOILPATHS


!! 7.2.2 CULVERT RESULTS
!!

!! 7.2.2.1 CREATE PATHS
! Get culvert corner nodes
CMSEL,S,COMPA_culvert
NSLA,S,1

N10=NODE(X4,Y2,0)
N11=NODE(X3,Y1,0)
N12=NODE(X3,Y2,0)
N13=NODE(X4,Y1,0)

N20=NODE(X5,Y2,0)
N21=NODE(X6,Y1,0)
N22=NODE(X6,Y2,0)
N23=NODE(X5,Y1,0)

N30=NODE(X4,Y3,0)
N31=NODE(X3,Y4,0)
N32=NODE(X3,Y3,0)
N33=NODE(X4,Y4,0)

N40=NODE(X5,Y3,0)
N41=NODE(X6,Y4,0)
N42=NODE(X6,Y3,0)
N43=NODE(X5,Y4,0)

! Virtual cross-sections: calculate geometric properties
secProp_I=(SewerWallThk**3)/12
secProp_W=secProp_I/(SewerWallThk/2)
secProp_A=SewerWallThk

! Number of shear force cross-sections
NSEL,S,LOC,X,X4,X5
NSEL,R,LOC,Y,Y1
*get,VSEC_horCount,NODE,,COUNT
NSEL,S,LOC,X,X4
NSEL,R,LOC,Y,Y2,Y3
*get,VSEC_verCount,NODE,,COUNT
CMSEL,S,COMPA_culvert
ESLA,S
NSLE,S,1

! Top slab
*del,TOP_M
*del,TOP_N
*del,TOP_V
*del,TOP_U
*del,TOP_D
*del,TOP_XG
*del,TOP_XV

PTHS2MN,N30,N40,N33,N43,'MN_Top','X',200,secProp_W,secProp_A,0
PTH2ARR,'XG','TOP_XG'
*voper,TOP_M,PTHS2MN_ARR_bendingMoment,DIV,1000
*voper,TOP_N,PTHS2MN_ARR_axialForce,DIV,1000

PTHS2V,N33,N43,N30,N40,'V_Top','XY',VSEC_horCount,,secProp_A,0
PTH2ARR,'XG','TOP_XV'
*voper,TOP_V,PTHS2V_ARR_shear,DIV,1000

PTH2DFL,N30,N40,,,'DF_Top','Y',100,,0
*vabs,1
*voper,TOP_U,PTH2DFL_ARR_disp,MULT,1000
*vabs,1
*voper,TOP_D,PTH2DFL_ARR_defl,MULT,1000
*vabs

! Bottom slab
*del,BOT_M
*del,BOT_N
*del,BOT_V
*del,BOT_U
*del,BOT_D
*del,BOT_XG
*del,BOT_XV

PTHS2MN,N20,N10,N23,N13,'MN_Bot','X',200,secProp_W,secProp_A,0
PTH2ARR,'XG','BOT_XG'
*voper,BOT_M,PTHS2MN_ARR_bendingMoment,DIV,1000
*voper,BOT_N,PTHS2MN_ARR_axialForce,DIV,1000

PTHS2V,N10,N20,N13,N23,'V_Bot','XY',VSEC_horCount,,secProp_A,0
PTH2ARR,'XG','BOT_XV'
*voper,BOT_V,PTHS2V_ARR_shear,DIV,1000

PTH2DFL,N10,N20,,,'DF_Bot','Y',100,,0
*vabs,1
*voper,BOT_U,PTH2DFL_ARR_disp,MULT,1000
*vabs,1
*voper,BOT_D,PTH2DFL_ARR_defl,MULT,1000
*vabs

! Left wall
*del,LFT_M
*del,LFT_N
*del,LFT_V
*del,LFT_YG
*del,LFT_YV

PTHS2MN,N10,N30,N12,N32,'MN_Lft','Y',200,secProp_W,secProp_A,0
PTH2ARR,'YG','LFT_YG'
*voper,LFT_M,PTHS2MN_ARR_bendingMoment,DIV,1000
*voper,LFT_N,PTHS2MN_ARR_axialForce,DIV,1000

PTHS2V,N12,N32,N10,N30,'V_Lft','XY',VSEC_verCount,,secProp_A,0
PTH2ARR,'YG','LFT_YV'
*voper,LFT_V,PTHS2V_ARR_shear,DIV,1000

! Right wall
*del,RGT_M
*del,RGT_N
*del,RGT_V
*del,RGT_YG
*del,RGT_YV

PTHS2MN,N40,N20,N42,N22,'MN_Rgt','Y',200,secProp_W,secProp_A,0
PTH2ARR,'YG','RGT_YG'
*voper,RGT_M,PTHS2MN_ARR_bendingMoment,DIV,1000
*voper,RGT_N,PTHS2MN_ARR_axialForce,DIV,1000

PTHS2V,N20,N40,N22,N42,'V_Rgt','XY',VSEC_verCount,,secProp_A,0
PTH2ARR,'YG','RGT_YV'
*voper,RGT_V,PTHS2V_ARR_shear,DIV,1000

! Inner walls
*if,CulvertCells,GT,1,THEN
  *del,INN_M_table
  *del,INN_N_table
  *del,INN_V_table
  *dim,INN_M_table,ARRAY,200,CulvertCells-1
  *dim,INN_N_table,ARRAY,200,CulvertCells-1
  *dim,INN_V_table,ARRAY,VSEC_verCount,CulvertCells-1
  *do,nthCell,1,CulvertCells-1,1
    xLeft=Xi(nthCell)
    xRight=Xj(nthCell)
    N_llc=NODE(xLeft,Y2,0)
    N_lrc=NODE(xRight,Y2,0)
    N_ulc=NODE(xLeft,Y3,0)
    N_urc=NODE(xRight,Y3,0)

    MNpathName=STRCAT('MN_In',CHRVAL(nthCell))
    VpathName=STRCAT('V_In',CHRVAL(nthCell))

    *del,nthINN_M
    *del,nthINN_N
    *del,nthINN_V
    *del,INN_YG
    *del,INN_YV

    PTHS2MN,N_lrc,N_urc,N_llc,N_ulc,MNpathName,'Y',200,secProp_W,secProp_A,0
    PTH2ARR,'YG','INN_YG'
    *voper,nthINN_M,PTHS2MN_ARR_bendingMoment,DIV,1000
    *voper,nthINN_N,PTHS2MN_ARR_axialForce,DIV,1000

    PTHS2V,N_llc,N_ulc,N_lrc,N_urc,VpathName,'XY',VSEC_verCount,,secProp_A,0
    PTH2ARR,'YG','INN_YV'
    *voper,nthINN_V,PTHS2V_ARR_shear,DIV,1000

    *do,nthValue,1,200,1
      INN_M_table(nthValue,nthCell)=nthINN_M(nthValue)
      INN_N_table(nthValue,nthCell)=nthINN_N(nthValue)
    *enddo
    *do,nthValue,1,VSEC_verCount,1
      INN_V_table(nthValue,nthCell)=nthINN_V(nthValue)
    *enddo
  *enddo
*endif


!! memo images
BOXCULVERT_V0_POSTCULVERT
/input , 'D:\Tools\Code\box-culvert-2D\_plot_soil_pres'       , mac
