! BOXCULVERT_V1_BC


!!
!!
!! 5. BOUNDARY CONDITIONS
!!
!!
/solu
antype,0,new
outres,all,last

!!
!! 5.1 SUPPORTS
!!
*if,SOLU_BCopt,EQ,0,THEN
  ! Apoio inferior
  CMSEL,S,COMPL_VerSupport
  NSLL,S,1
  D,ALL,UY,0

  ! Apoios laterais
  CMSEL,S,COMPL_HorSupport
  NSLL,S,1
  D,ALL,UX,0
*endif



!!
!! 5.2 FIRST LOAD STEP: DEAD WEIGHT
!!
! Peso próprio
ACEL,,LOAD_g

! Write load step
ALLSEL
NSUBST,NINT(SOLU_nSubstep/1)
*if,SOLU_largeDisp,EQ,1,THEN
  NLGEOM,ON
*else
  NLGEOM,OFF
*endif
time,1
solve


!!
!! 5.3 SECOND LOAD STEP: LIVE LOADS
!!

cmsel,s,COMPN_surface
*get , ySurface , node ,  , mxloc , y
*get , xMin     , node ,  , mnloc , x
*get , xMax     , node ,  , mxloc , x

*do,nthPos,1,LOADTRAIN_posCount,1

  ! Inherit BCs from 1st load step
  /solu
  allsel
  f,COMPN_surface,fy,-0.1

  ! Point loads
  lsNum  = nthPos+1
  offset = LOADTRAIN_positions(nthPos)

  *do,nthLoad,1,LOADTRAIN_VAR_count,1
    xPos = offset+LOADTRAIN_ARR_positions(nthLoad)
    qVal = LOADTRAIN_ARR_loads(nthLoad)

    *if,xPos,le,xMin,or,xPos,ge,xMax,cycle

    cmsel,s,COMPN_surface
    fNode = node(xPos,ySurface,0)
    f,fNode,fy,-qVal
  *enddo

  ! Uniform load
  lsel,s,loc,y,ySurface
  sfl,all,pres,LOAD_Uniform

  ! Capture image: loads
  allsel
  eplot
  /edge,all,1
  /device,vector,1
  /pbc , u    ,      , 0
  /pbc , rot  ,      , 0
  /pbc , temp ,      , 0
  /pbc , pres ,      , 0
  /pbc , f    ,      , 2
  /pbc , m    ,      , 0
  /psf , defa ,      , 1 , 0 , 1
  /psf , pres , norm , 2 , 0 , 1
  /pbf , defa ,      , 1
  eplot
  /cwd,'%imgFolderPath(1)%'
  takepic,'LOAD_LS%lsNum%',1000
  /cwd,'%currDir(1)%'
  /device,vector,off
  /edge,all,0
  /pbc,f,,0

  allsel
  time,lsNum
  kbc,0
  solve

*enddo

lastLS = LOADTRAIN_posCount+1

! Capturar imagem: malha de elementos finitos
ALLSEL
/pnum,MAT,1
/number,1
/edge,ALL,0
EPLOT
/cwd,'%imgFolderPath(1)%'
TAKEPIC,'MESH_01'
/cwd,'%currDir(1)%'
