! BOXCULVERT_V0_POSTCULVERT


! Populate path name/label arrays
slabCount = 4+CulvertCells-1

*del , path_names    ,      , nopr
*del , path_labels_m ,      , nopr
*del , path_labels_n ,      , nopr
*del , path_labels_v ,      , nopr
*dim , path_names    , char , slabCount*2
*dim , path_labels_m , char , slabCount*2
*dim , path_labels_n , char , slabCount*2
*dim , path_labels_v , char , slabCount*2

path_names(1)    = 'ROOF'   , 'ROOF'   , 'FLOOR'  , 'FLOOR'  , 'LEFT'   , 'LEFT'   , 'RIGHT'  , 'RIGHT'
path_labels_m(1) = 'MP_MIN' , 'MP_MAX' , 'MP_MIN' , 'MP_MAX' , 'MP_MIN' , 'MP_MAX' , 'MP_MIN' , 'MP_MAX'
path_labels_n(1) = 'N_MIN'  , 'N_MAX'  , 'N_MIN'  , 'N_MAX'  , 'N_MIN'  , 'N_MAX'  , 'N_MIN'  , 'N_MAX'
path_labels_v(1) = 'V_MIN'  , 'V_MAX'  , 'V_MIN'  , 'V_MAX'  , 'V_MIN'  , 'V_MAX'  , 'V_MIN'  , 'V_MAX'

*do,nthIWall,1,CulvertCells-1,1
  idx                = 8+(2*nthIWall-1)
  path_names(idx)    = 'INW%nthIWall%' , 'INW%nthIWall%'
  path_labels_m(idx) = 'MP_MIN'        , 'MP_MAX'
  path_labels_n(idx) = 'N_MIN'         , 'N_MAX'
  path_labels_v(idx) = 'V_MIN'         , 'V_MAX'
*enddo

! Plot bending moment
BOXCULVERT_V0_PTHPLOTS , 'BENDING MOMENT [kNm]' , 2*CulvertCells , 'path_names' , 'path_labels_m' , 'memo_CULVERT_M'

! Plot axial force
BOXCULVERT_V0_PTHPLOTS , 'AXIAL FORCE [kN]'     , 2*CulvertCells , 'path_names' , 'path_labels_n' , 'memo_CULVERT_N'

! Plot shear force
BOXCULVERT_V0_PTHPLOTS , 'SHEAR FORCE [kN]'     , 2*CulvertCells , 'path_names' , 'path_labels_v' , 'memo_CULVERT_V'

! Plot vertical displacement
/annot,dele
view1w
windefa,1
wincln,1
clims
boldfont,1
/view,1,0,0,1
/plopts,leg3,on
/udoc,1,cntr,right
/gformat,f,1,1
/dscale,1,1

cmsel,s,COMPA_culvert
esla,s
nsle,s,1
/auto,1
pldisp
/user,1
/dist,1,1.2,1

wintitle,1,' ','VERTICAL DISPLACEMENTS [mm]',' ',,1,13

go2png,1200
  allsel
  /device,vector,on
  /edge,,1
  pldisp
  /noerase
  /device,vector,off
  cmsel,s,COMPA_culvert
  esla
  nsle,,1
  cleanplot,'plnsol','u','y',,,,,,1e3
endpng,'memo_CULVERT_UY'

/erase
/annot,dele
boldfont
clims
view1w
